import { useState, useRef } from 'react';
import { FileDown, FileText, Code2, Clipboard, Check, ChevronDown } from 'lucide-react';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import html2canvas from 'html2canvas';
import mermaid from 'mermaid';

function ExportMenu({ result, idea }) {
  const [open, setOpen] = useState(false);
  const [copiedAll, setCopiedAll] = useState(false);
  const menuRef = useRef(null);

  const buildMarkdown = () => {
    let md = `# System Architecture: ${idea}\n\n`;
    md += `> Generated on ${new Date().toLocaleDateString()}\n\n`;
    md += `## Features\n`;
    result.features?.forEach(f => { md += `- **[${f.priority}]** ${f.name}\n`; });
    md += `\n## Database Schema\n`;
    result.database?.forEach(table => {
      md += `### ${table.table}\n`;
      md += `**Fields:** ${table.fields.join(', ')}\n`;
      if (table.relationships?.length) md += `**Relationships:** ${table.relationships.join(', ')}\n`;
      md += '\n';
    });
    md += `## REST APIs\n`;
    result.apis?.forEach(api => {
      md += `- \`${api.method}\` **${api.endpoint}** — ${api.description}\n`;
    });
    md += `\n## Architecture\n`;
    md += `**Type:** ${result.architecture?.type}\n`;
    md += `**Components:** ${result.architecture?.components?.join(', ')}\n\n`;
    md += `### Tech Stack\n`;
    md += `| Layer | Technology |\n|---|---|\n`;
    md += `| Frontend | ${result.architecture?.tech_stack?.frontend} |\n`;
    md += `| Backend | ${result.architecture?.tech_stack?.backend} |\n`;
    md += `| Database | ${result.architecture?.tech_stack?.database} |\n\n`;
    md += `## Roadmap\n`;
    result.roadmap?.forEach(phase => {
      md += `### ${phase.phase}\n`;
      phase.tasks?.forEach(t => { md += `- ${t}\n`; });
      md += '\n';
    });
    md += `## Estimation\n`;
    md += `- **Hours:** ${result.estimation?.hours}\n`;
    md += `- **Team Size:** ${result.estimation?.team_size}\n`;
    md += `- **Cost:** ${result.estimation?.cost}\n\n`;
    md += `## ER Diagram\n\`\`\`mermaid\n${result.erDiagram}\n\`\`\`\n\n`;
    md += `## Architecture Diagram\n\`\`\`mermaid\n${result.architectureDiagram}\n\`\`\`\n`;
    return md;
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'architecture.json'; a.click();
    URL.revokeObjectURL(url);
    toast.success('JSON exported!');
    setOpen(false);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([buildMarkdown()], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'architecture.md'; a.click();
    URL.revokeObjectURL(url);
    toast.success('Markdown exported!');
    setOpen(false);
  };

  const handleCopyAll = () => {
    navigator.clipboard.writeText(buildMarkdown()).then(() => {
      setCopiedAll(true);
      setTimeout(() => setCopiedAll(false), 2000);
      toast.success('Copied to clipboard!');
    });
    setOpen(false);
  };

  const handleDownloadPDF = async () => {
    const loadingToast = toast.loading('Generating PDF with diagrams...');
    
    try {
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - 2 * margin;
      let currentPage = 1;

      // Helper: Add page number footer
      const addFooter = () => {
        doc.setFontSize(9);
        doc.setTextColor(128, 128, 128);
        doc.text(
          `Page ${currentPage} | Generated by AI Architecture Generator`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
        currentPage++;
      };

      // Helper: Add new page with footer
      const addNewPage = () => {
        addFooter();
        doc.addPage();
      };

      // Cover Page
      doc.setFillColor(37, 99, 235);
      doc.rect(0, 0, pageWidth, pageHeight, 'F');
      
      doc.setFontSize(32);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text('System Architecture', pageWidth / 2, 80, { align: 'center' });
      
      doc.setFontSize(16);
      doc.setFont('helvetica', 'normal');
      const ideaLines = doc.splitTextToSize(idea, contentWidth - 40);
      doc.text(ideaLines, pageWidth / 2, 100, { align: 'center', maxWidth: contentWidth - 40 });
      
      doc.setFontSize(12);
      doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, pageHeight - 60, { align: 'center' });
      
      doc.setFontSize(10);
      doc.setTextColor(200, 200, 200);
      doc.text('Powered by AI Architecture Generator', pageWidth / 2, pageHeight - 40, { align: 'center' });

      // Table of Contents
      addNewPage();
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('Table of Contents', margin, 30);
      
      const tocItems = [
        '1. Features',
        '2. Technology Stack',
        '3. Architecture Overview',
        '4. Database Schema',
        '5. REST API Endpoints',
        '6. Development Roadmap',
        '7. Project Estimation',
        '8. ER Diagram',
        '9. Architecture Diagram'
      ];
      
      doc.setFontSize(11);
      doc.setTextColor(60, 60, 60);
      doc.setFont('helvetica', 'normal');
      let tocY = 50;
      tocItems.forEach(item => {
        doc.text(item, margin + 5, tocY);
        tocY += 8;
      });

      // 1. Features Section
      addNewPage();
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('1. Features', margin, 30);
      
      if (result.features?.length) {
        const featuresData = result.features.map(f => [
          f.priority || 'N/A',
          f.name || '',
          f.description || ''
        ]);
        
        doc.autoTable({
          startY: 40,
          head: [['Priority', 'Feature', 'Description']],
          body: featuresData,
          theme: 'striped',
          headStyles: { fillColor: [37, 99, 235], fontSize: 11, fontStyle: 'bold' },
          styles: { fontSize: 10, cellPadding: 4 },
          columnStyles: {
            0: { cellWidth: 25 },
            1: { cellWidth: 50 },
            2: { cellWidth: contentWidth - 75 }
          },
          margin: { left: margin, right: margin }
        });
      }

      // 2. Tech Stack Section
      addNewPage();
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('2. Technology Stack', margin, 30);
      
      const techStackData = [
        ['Frontend', result.architecture?.tech_stack?.frontend || 'N/A'],
        ['Backend', result.architecture?.tech_stack?.backend || 'N/A'],
        ['Database', result.architecture?.tech_stack?.database || 'N/A'],
        ['Deployment', result.architecture?.tech_stack?.deployment || 'N/A']
      ];
      
      doc.autoTable({
        startY: 40,
        head: [['Layer', 'Technology']],
        body: techStackData,
        theme: 'grid',
        headStyles: { fillColor: [37, 99, 235], fontSize: 11, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: {
          0: { cellWidth: 50, fontStyle: 'bold' },
          1: { cellWidth: contentWidth - 50 }
        },
        margin: { left: margin, right: margin }
      });

      // 3. Architecture Overview
      addNewPage();
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('3. Architecture Overview', margin, 30);
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60, 60, 60);
      doc.text('Architecture Type:', margin, 50);
      doc.setFont('helvetica', 'normal');
      doc.text(result.architecture?.type || 'N/A', margin + 50, 50);
      
      doc.setFont('helvetica', 'bold');
      doc.text('Components:', margin, 60);
      doc.setFont('helvetica', 'normal');
      const components = result.architecture?.components?.join(', ') || 'N/A';
      const componentLines = doc.splitTextToSize(components, contentWidth - 50);
      doc.text(componentLines, margin + 50, 60);

      // 4. Database Schema
      addNewPage();
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('4. Database Schema', margin, 30);
      
      if (result.database?.length) {
        let tableY = 40;
        result.database.forEach((table) => {
          if (tableY > pageHeight - 60) {
            addNewPage();
            tableY = 30;
          }
          
          doc.setFontSize(14);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(37, 99, 235);
          doc.text(`${table.table}`, margin, tableY);
          tableY += 10;
          
          const tableData = [
            ['Fields', table.fields?.join(', ') || 'N/A'],
            ['Relationships', table.relationships?.join(', ') || 'None']
          ];
          
          doc.autoTable({
            startY: tableY,
            body: tableData,
            theme: 'plain',
            styles: { fontSize: 10, cellPadding: 3 },
            columnStyles: {
              0: { cellWidth: 40, fontStyle: 'bold', textColor: [60, 60, 60] },
              1: { cellWidth: contentWidth - 40 }
            },
            margin: { left: margin, right: margin }
          });
          
          tableY = doc.lastAutoTable.finalY + 15;
        });
      }

      // 5. REST API Endpoints
      addNewPage();
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('5. REST API Endpoints', margin, 30);
      
      if (result.apis?.length) {
        const apiData = result.apis.map(api => [
          api.method || 'GET',
          api.endpoint || '',
          api.description || ''
        ]);
        
        doc.autoTable({
          startY: 40,
          head: [['Method', 'Endpoint', 'Description']],
          body: apiData,
          theme: 'striped',
          headStyles: { fillColor: [37, 99, 235], fontSize: 11, fontStyle: 'bold' },
          styles: { fontSize: 9, cellPadding: 4 },
          columnStyles: {
            0: { cellWidth: 20, fontStyle: 'bold' },
            1: { cellWidth: 60 },
            2: { cellWidth: contentWidth - 80 }
          },
          margin: { left: margin, right: margin }
        });
      }

      // 6. Development Roadmap
      addNewPage();
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('6. Development Roadmap', margin, 30);
      
      if (result.roadmap?.length) {
        let roadmapY = 40;
        result.roadmap.forEach((phase, idx) => {
          if (roadmapY > pageHeight - 60) {
            addNewPage();
            roadmapY = 30;
          }
          
          doc.setFontSize(14);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(37, 99, 235);
          doc.text(`Phase ${idx + 1}: ${phase.phase}`, margin, roadmapY);
          roadmapY += 8;
          
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(60, 60, 60);
          
          phase.tasks?.forEach(task => {
            const taskLines = doc.splitTextToSize(`• ${task}`, contentWidth - 10);
            if (roadmapY + taskLines.length * 5 > pageHeight - 30) {
              addNewPage();
              roadmapY = 30;
            }
            doc.text(taskLines, margin + 5, roadmapY);
            roadmapY += taskLines.length * 5 + 2;
          });
          
          roadmapY += 8;
        });
      }

      // 7. Project Estimation
      addNewPage();
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(37, 99, 235);
      doc.text('7. Project Estimation', margin, 30);
      
      const estimationData = [
        ['Development Hours', result.estimation?.hours || 'N/A'],
        ['Team Size', result.estimation?.team_size || 'N/A'],
        ['Estimated Cost', result.estimation?.cost || 'N/A'],
        ['Timeline', result.estimation?.timeline || 'N/A']
      ];
      
      doc.autoTable({
        startY: 40,
        body: estimationData,
        theme: 'grid',
        styles: { fontSize: 11, cellPadding: 6 },
        columnStyles: {
          0: { cellWidth: 60, fontStyle: 'bold', fillColor: [240, 240, 240] },
          1: { cellWidth: contentWidth - 60, fontSize: 12 }
        },
        margin: { left: margin, right: margin }
      });

      // 8. ER Diagram
      if (result.erDiagram) {
        addNewPage();
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(37, 99, 235);
        doc.text('8. ER Diagram', margin, 30);
        
        try {
          const erContainer = document.createElement('div');
          erContainer.style.position = 'absolute';
          erContainer.style.left = '-9999px';
          erContainer.style.background = 'white';
          erContainer.style.padding = '20px';
          erContainer.innerHTML = `<div class="mermaid">${result.erDiagram}</div>`;
          document.body.appendChild(erContainer);
          
          await mermaid.run({ nodes: erContainer.querySelectorAll('.mermaid') });
          
          const canvas = await html2canvas(erContainer, { 
            backgroundColor: '#ffffff',
            scale: 2 
          });
          const imgData = canvas.toDataURL('image/png');
          
          const imgWidth = contentWidth;
          const imgHeight = (canvas.height * imgWidth) / canvas.width;
          
          doc.addImage(imgData, 'PNG', margin, 45, imgWidth, Math.min(imgHeight, pageHeight - 80));
          
          document.body.removeChild(erContainer);
        } catch (error) {
          console.error('Error rendering ER diagram:', error);
          doc.setFontSize(10);
          doc.setTextColor(128, 128, 128);
          doc.text('ER Diagram could not be rendered', margin, 50);
        }
      }

      // 9. Architecture Diagram
      if (result.architectureDiagram) {
        addNewPage();
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(37, 99, 235);
        doc.text('9. Architecture Diagram', margin, 30);
        
        try {
          const archContainer = document.createElement('div');
          archContainer.style.position = 'absolute';
          archContainer.style.left = '-9999px';
          archContainer.style.background = 'white';
          archContainer.style.padding = '20px';
          archContainer.innerHTML = `<div class="mermaid">${result.architectureDiagram}</div>`;
          document.body.appendChild(archContainer);
          
          await mermaid.run({ nodes: archContainer.querySelectorAll('.mermaid') });
          
          const canvas = await html2canvas(archContainer, { 
            backgroundColor: '#ffffff',
            scale: 2 
          });
          const imgData = canvas.toDataURL('image/png');
          
          const imgWidth = contentWidth;
          const imgHeight = (canvas.height * imgWidth) / canvas.width;
          
          doc.addImage(imgData, 'PNG', margin, 45, imgWidth, Math.min(imgHeight, pageHeight - 80));
          
          document.body.removeChild(archContainer);
        } catch (error) {
          console.error('Error rendering architecture diagram:', error);
          doc.setFontSize(10);
          doc.setTextColor(128, 128, 128);
          doc.text('Architecture Diagram could not be rendered', margin, 50);
        }
      }

      // Add footer to last page
      addFooter();

      // Save PDF
      const fileName = `architecture_${idea.substring(0, 30).replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.pdf`;
      doc.save(fileName);
      
      toast.success('PDF exported successfully!', { id: loadingToast });
      setOpen(false);
    } catch (error) {
      console.error('PDF generation error:', error);
      toast.error('Failed to generate PDF. Please try again.', { id: loadingToast });
    }
  };

  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-blue-600 to-cyan-500 text-white rounded-lg hover:from-blue-700 hover:to-cyan-600 transition-all shadow-md"
      >
        <FileDown size={16} />
        Export
        <ChevronDown size={14} className={`transition-transform ${open ? 'rotate-180' : ''}`} />
      </button>

      {open && (
        <>
          <div className="fixed inset-0 z-10" onClick={() => setOpen(false)} />
          <div className="absolute right-0 mt-2 w-52 bg-white dark:bg-gray-800 rounded-xl shadow-2xl border border-gray-100 dark:border-gray-700 z-20 overflow-hidden">
            <button onClick={handleDownloadPDF} className="flex items-center gap-3 w-full px-4 py-3 text-sm text-gray-700 dark:text-gray-200 hover:bg-red-50 dark:hover:bg-red-900/20 transition">
              <FileDown size={16} className="text-red-500" /> Export as PDF
            </button>
            <button onClick={handleDownloadMarkdown} className="flex items-center gap-3 w-full px-4 py-3 text-sm text-gray-700 dark:text-gray-200 hover:bg-green-50 dark:hover:bg-green-900/20 transition">
              <FileText size={16} className="text-green-500" /> Export as Markdown
            </button>
            <button onClick={handleDownloadJSON} className="flex items-center gap-3 w-full px-4 py-3 text-sm text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-blue-900/20 transition">
              <Code2 size={16} className="text-blue-500" /> Export as JSON
            </button>
            <div className="border-t border-gray-100 dark:border-gray-700" />
            <button onClick={handleCopyAll} className="flex items-center gap-3 w-full px-4 py-3 text-sm text-gray-700 dark:text-gray-200 hover:bg-purple-50 dark:hover:bg-purple-900/20 transition">
              {copiedAll ? <Check size={16} className="text-purple-500" /> : <Clipboard size={16} className="text-purple-500" />}
              Copy All (Markdown)
            </button>
          </div>
        </>
      )}
    </div>
  );
}

export default ExportMenu;
